[build.env]
passthrough = [
    "CARGO_INCREMENTAL",
    "CARGO_PROFILE_DEV_DEBUG", 
    "CARGO_TERM_COLOR",
    "RUST_BACKTRACE",
    "RUSTFLAGS",
    "CARGO_UNSTABLE_SPARSE_REGISTRY",
    "CARGO_REGISTRIES_CRATES_IO_PROTOCOL"
]

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:edge"