name: Build Artifacts

on:
  push:
    branches: [master, main]
    tags:
      - 'v*'
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: chef-de-vibe-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: chef-de-vibe-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: chef-de-vibe-macos-arm64
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
          
      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config openssl@3
          
      - name: Build frontend
        run: |
          cd frontend
          npm ci --legacy-peer-deps
          npm run build
          
      - name: Build Rust binary
        run: |
          cargo build --release --target ${{ matrix.target }}
          
      - name: Create archive
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" = "Windows" ]; then
            cp target/${{ matrix.target }}/release/chef-de-vibe.exe dist/
            7z a ${{ matrix.artifact_name }}.zip dist/*
          else
            cp target/${{ matrix.target }}/release/chef-de-vibe dist/
            tar -czf ${{ matrix.artifact_name }}.tar.gz -C dist chef-de-vibe
          fi
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}.*
          
  test-homebrew:
    needs: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
        
      - name: Test formula installation
        run: |
          # Test installing from the local formula
          brew install --HEAD --build-from-source ./Formula/chef-de-vibe.rb
          
      - name: Test binary
        run: |
          # Check that the binary was installed
          which chef-de-vibe
          # Try to get version or help
          chef-de-vibe --help || true
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        
      - name: Generate checksums
        run: |
          # Generate SHA256 checksums for all artifacts
          find . -name "*.tar.gz" -o -name "*.zip" | xargs sha256sum > sha256sums.txt
          cat sha256sums.txt
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            chef-de-vibe-*/*.tar.gz
            chef-de-vibe-*/*.zip
            sha256sums.txt
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}