name: Build and Push Docker Image

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
    paths-ignore:
      - '**/*.md'
  workflow_call:

jobs:
  test:
    uses: ./.github/workflows/test.yml
    
  build:
    runs-on: ${{ matrix.runner }}
    needs: [test]
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: nuhotetotniksvoboden/chef-de-vibe
        tags: |
          type=ref,event=branch,prefix=pre-
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=pre-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Build and push Docker image by digest
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ matrix.platform }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=image,name=nuhotetotniksvoboden/chef-de-vibe,push-by-digest=true,name-canonical=true,push=true
        provenance: false
        
    - name: Export digest
      run: |
        mkdir -p /tmp/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "/tmp/digests/${digest#sha256:}"
        
    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ matrix.platform == 'linux/amd64' && 'amd64' || 'arm64' }}
        path: /tmp/digests/*
        if-no-files-found: error
        retention-days: 1
        
  merge-and-push:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:
    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: /tmp/digests
        pattern: digests-*
        merge-multiple: true
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: nuhotetotniksvoboden/chef-de-vibe
        tags: |
          type=ref,event=branch,prefix=pre-
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=pre-
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Create manifest list and push
      working-directory: /tmp/digests
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf 'nuhotetotniksvoboden/chef-de-vibe@sha256:%s ' *)
          
    - name: Inspect image
      run: |
        docker buildx imagetools inspect nuhotetotniksvoboden/chef-de-vibe:${{ steps.meta.outputs.version }}