name: Create Releases

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]

jobs:
  build-docker:
    uses: ./.github/workflows/docker-build-push.yml
    secrets: inherit
    
  create-release:
    runs-on: ubuntu-latest
    needs: [build-docker]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Get commit info
      id: commit
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "message=$(git log -1 --pretty=%B | head -n1)" >> $GITHUB_OUTPUT
        echo "date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
        
    - name: Check if tag
      id: check_tag
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "is_tag=true" >> $GITHUB_OUTPUT
          echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "is_tag=false" >> $GITHUB_OUTPUT
          echo "tag_name=pre-${{ steps.commit.outputs.sha }}" >> $GITHUB_OUTPUT
        fi
        
    - name: Generate release notes
      id: notes
      run: |
        if [[ "${{ steps.check_tag.outputs.is_tag }}" == "true" ]]; then
          # For tagged releases, get changes since last tag
          LAST_TAG=$(git tag --sort=-version:refname | grep -v "^pre-" | head -n2 | tail -n1 || echo "")
          if [[ -n "$LAST_TAG" ]]; then
            CHANGES=$(git log --pretty=format:"- %s (%h)" ${LAST_TAG}..HEAD)
          else
            CHANGES=$(git log --pretty=format:"- %s (%h)" --max-count=10)
          fi
        else
          # For pre-releases, just show the current commit
          CHANGES="- ${{ steps.commit.outputs.message }} (${{ steps.commit.outputs.sha }})"
        fi
        
        if [[ "${{ steps.check_tag.outputs.is_tag }}" == "true" ]]; then
          DOCKER_IMAGE="nuhotetotniksvoboden/chef-de-vibe:${{ steps.check_tag.outputs.tag_name }}"
        else
          DOCKER_IMAGE="nuhotetotniksvoboden/chef-de-vibe:pre-${{ steps.commit.outputs.sha }}"
        fi
        
        cat << EOF > release_notes.md
        ## Docker Image
        
        \`\`\`bash
        docker pull ${DOCKER_IMAGE}
        docker run -p 8080:8080 ${DOCKER_IMAGE}
        \`\`\`
        
        **Docker Hub:** https://hub.docker.com/r/nuhotetotniksvoboden/chef-de-vibe/tags
        
        ## Changes
        
        ${CHANGES}
        
        ---
        Built from commit: \`${{ steps.commit.outputs.sha }}\`  
        Build date: ${{ steps.commit.outputs.date }}
        EOF
        
    - name: Create pre-release
      if: steps.check_tag.outputs.is_tag == 'false'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.check_tag.outputs.tag_name }}
        name: "Pre-release ${{ steps.commit.outputs.sha }}"
        body_path: release_notes.md
        prerelease: true
        make_latest: false
        
    - name: Create release
      if: steps.check_tag.outputs.is_tag == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.check_tag.outputs.tag_name }}
        name: "Release ${{ steps.check_tag.outputs.tag_name }}"
        body_path: release_notes.md
        prerelease: false
        make_latest: true